import type { LucideIcon } from "lucide-react"
import {
  AArrowDown,
  Accessibility,
  Airplay,
  AlarmClockMinus,
  AlarmSmoke,
  AlignCenterVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalJustifyCenter,
  AlignHorizontalSpaceAround,
  AlignStartVertical,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyStart,
  Ambulance,
  Amphora,
  Annoyed,
  Aperture,
  Apple,
  ArchiveX,
  ArrowBigDownDash,
  ArrowBigRight,
  ArrowBigUpDash,
  ArrowDown10,
  ArrowDownLeft,
  ArrowDownToDot,
  ArrowDownWideNarrow,
  ArrowLeftFromLine,
  ArrowRight,
  ArrowRightToLine,
  ArrowUp10,
  ArrowUpFromDot,
  ArrowUpNarrowWide,
  ArrowUpWideNarrow,
  Asterisk,
  AudioLines,
  Axe,
  Backpack,
  BadgeCent,
  BadgeEuro,
  BadgeJapaneseYen,
  BadgePlus,
  BadgeRussianRuble,
  BadgeX,
  Ban,
  Banknote,
  BanknoteX,
  Baseline,
  BatteryCharging,
  BatteryMedium,
  Beaker,
  Bed,
  Beef,
  Bell,
  BellMinus,
  BellRing,
  BetweenVerticalEnd,
  Bike,
  Biohazard,
  Bitcoin,
  Blocks,
  BluetoothOff,
  Bolt,
  Book,
  BookAudio,
  BookDashed,
  BookHeart,
  BookLock,
  BookOpen,
  BookPlus,
  BookType,
  BookX,
  BookmarkMinus,
  BoomBox,
  BotOff,
  Box,
  Brackets,
  BrainCog,
  BrickWallShield,
  BriefcaseConveyorBelt,
  Brush,
  Bug,
  Building,
  Cable,
  CakeSlice,
  Calendar1,
  CalendarCheck,
  CalendarDays,
  CalendarMinus,
  CalendarRange,
  CalendarX,
  CameraOff,
  CandyOff,
  Captions,
  CarFront,
  CardSim,
  CaseSensitive,
  Cast,
  Cctv,
  ChartBarBig,
  ChartBarStacked,
  ChartColumnBig,
  ChartColumnStacked,
  ChartNetwork,
  ChartNoAxesColumnIncreasing,
  ChartPie,
  Check,
  ChefHat,
  ChessKing,
  ChessQueen,
  ChevronFirst,
  ChevronRight,
  ChevronsDownUp,
  ChevronsLeftRightEllipsis,
  ChevronsUp,
  Church,
  Circle,
  CircleArrowLeft,
  CircleArrowOutUpLeft,
  CircleArrowUp,
  CircleChevronDown,
  CircleChevronUp,
  CircleDollarSign,
  CircleEllipsis,
  CircleFadingPlus,
  CircleOff,
  CirclePause,
  CirclePlay,
  CirclePower,
  CircleSmall,
  CircleUser,
  CircuitBoard,
  Clipboard,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardPlus,
  Clock,
  Clock11,
  Clock5,
  Clock8,
  ClockArrowDown,
  ClockFading,
  Cloud,
  CloudCheck,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudSnow,
  CloudSync,
  Clover,
  CodeXml,
  Coffee,
  Columns3,
  Combine,
  Component,
  Cone,
  ContactRound,
  Cookie,
  CopyCheck,
  CopySlash,
  Copyright,
  CornerLeftDown,
  CornerRightUp,
  Cpu,
  Croissant,
  Crosshair,
  CupSoda,
  Dam,
  DatabaseSearch,
  DecimalsArrowRight,
  Diameter,
  DiamondPercent,
  Dice3,
  Dice6,
  Disc,
  Divide,
  Dock,
  Donut,
  DoorOpen,
  DraftingCompass,
  Drill,
  DropletOff,
  Drumstick,
  EarOff,
  Eclipse,
  EggOff,
  Equal,
  Eraser,
  EvCharger,
  Eye,
  Facebook,
  FastForward,
  FerrisWheel,
  FileArchive,
  FileBox,
  FileChartColumn,
  FileChartPie,
  FileClock,
  FileCog,
  FileDown,
  FileHeart,
  FileKey,
  FileMinusCorner,
  FilePen,
  FilePlus,
  FileScan,
  FileSignal,
  FileStack,
  FileText,
  FileUp,
  FileVolume,
  Files,
  FireExtinguisher,
  FishSymbol,
  FlagOff,
  Flame,
  FlashlightOff,
  FlaskRound,
  Flower,
  FoldVertical,
  FolderCheck,
  FolderCode,
  FolderDown,
  FolderInput,
  FolderLock,
  FolderOpenDot,
  FolderPlus,
  FolderSymlink,
  FolderUp,
  Footprints,
  Forward,
  Frown,
  Funnel,
  GalleryHorizontal,
  GalleryVertical,
  GamepadDirectional,
  Gem,
  Gift,
  GitBranchPlus,
  GitCompare,
  GitGraph,
  GitPullRequestArrow,
  GitPullRequestCreateArrow,
  Gitlab,
  Globe,
  Goal,
  Grape,
  Grid2x2X,
  GripHorizontal,
  Guitar,
  Hammer,
  HandFist,
  HandHelping,
  Handbag,
  HardDriveDownload,
  Hash,
  Hd,
  Heading1,
  Heading5,
  Headphones,
  HeartCrack,
  HeartOff,
  Heater,
  Highlighter,
  HopOff,
  Hourglass,
  HousePlug,
  IceCreamBowl,
  IdCard,
  ImageDown,
  ImagePlay,
  ImageUpscale,
  Inbox,
  Info,
  Italic,
  JapaneseYen,
  Kayak,
  KeySquare,
  KeyboardOff,
  LampDesk,
  LampWallUp,
  Languages,
  LaptopMinimalCheck,
  Laugh,
  LayoutDashboard,
  LayoutPanelLeft,
  Leaf,
  Library,
  Ligature,
  LineSquiggle,
  Linkedin,
  ListChecks,
  ListCollapse,
  ListFilterPlus,
  ListMinus,
  ListPlus,
  ListTodo,
  ListX,
  LoaderPinwheel,
  LocateOff,
  LockKeyholeOpen,
  LogOut,
  Mail,
  MailOpen,
  MailSearch,
  Mailbox,
  MapMinus,
  MapPinCheckInside,
  MapPinMinusInside,
  MapPinPlus,
  MapPinXInside,
  Mars,
  Maximize,
  MegaphoneOff,
  Menu,
  MessageCircleCode,
  MessageCircleMore,
  MessageCircleQuestionMark,
  MessageCircleX,
  MessageSquareDashed,
  MessageSquareHeart,
  MessageSquareOff,
  MessageSquareReply,
  MessageSquareWarning,
  Mic,
  Microchip,
  Milestone,
  Minimize,
  MonitorCheck,
  MonitorDot,
  MonitorPause,
  MonitorSpeaker,
  MonitorX,
  Motorbike,
  Mouse,
  MousePointer2Off,
  Move,
  MoveDown,
  MoveHorizontal,
  MoveUp,
  MoveVertical,
  Music4,
  NavigationOff,
  Nfc,
  NotebookPen,
  NotepadText,
  NutOff,
  OctagonMinus,
  Omega,
  Origami,
  PackageMinus,
  PackageSearch,
  PaintRoller,
  Palette,
  PanelBottomClose,
  PanelLeft,
  PanelLeftOpen,
  PanelRightClose,
  PanelTop,
  PanelTopDashed,
  PanelsRightBottom,
  Parentheses,
  Pause,
  Pen,
  PenTool,
  PencilOff,
  Percent,
  Phone,
  PhoneIncoming,
  PhoneOutgoing,
  Pickaxe,
  Pilcrow,
  Pill,
  PinOff,
  Plane,
  Play,
  Plus,
  Podcast,
  Popcorn,
  Power,
  Printer,
  Projector,
  Pyramid,
  Rabbit,
  Radical,
  RadioTower,
  Rainbow,
  Receipt,
  ReceiptIndianRupee,
  ReceiptRussianRuble,
  ReceiptTurkishLira,
  RectangleGoggles,
  Recycle,
  RefreshCcw,
  RefreshCwOff,
  RemoveFormatting,
  Replace,
  ReplyAll,
  Rocket,
  Rose,
  RotateCcwKey
} from "lucide-react"

export const ICON_OPTIONS: { name: string; icon: any }[] = [
  { name: "AArrowDown", icon: AArrowDown },
  { name: "Accessibility", icon: Accessibility },
  { name: "Airplay", icon: Airplay },
  { name: "AlarmClockMinus", icon: AlarmClockMinus },
  { name: "AlarmSmoke", icon: AlarmSmoke },
  { name: "AlignCenterVertical", icon: AlignCenterVertical },
  { name: "AlignHorizontalDistributeCenter", icon: AlignHorizontalDistributeCenter },
  { name: "AlignHorizontalJustifyCenter", icon: AlignHorizontalJustifyCenter },
  { name: "AlignHorizontalSpaceAround", icon: AlignHorizontalSpaceAround },
  { name: "AlignStartVertical", icon: AlignStartVertical },
  { name: "AlignVerticalDistributeStart", icon: AlignVerticalDistributeStart },
  { name: "AlignVerticalJustifyStart", icon: AlignVerticalJustifyStart },
  { name: "Ambulance", icon: Ambulance },
  { name: "Amphora", icon: Amphora },
  { name: "Annoyed", icon: Annoyed },
  { name: "Aperture", icon: Aperture },
  { name: "Apple", icon: Apple },
  { name: "ArchiveX", icon: ArchiveX },
  { name: "ArrowBigDownDash", icon: ArrowBigDownDash },
  { name: "ArrowBigRight", icon: ArrowBigRight },
  { name: "ArrowBigUpDash", icon: ArrowBigUpDash },
  { name: "ArrowDown10", icon: ArrowDown10 },
  { name: "ArrowDownLeft", icon: ArrowDownLeft },
  { name: "ArrowDownToDot", icon: ArrowDownToDot },
  { name: "ArrowDownWideNarrow", icon: ArrowDownWideNarrow },
  { name: "ArrowLeftFromLine", icon: ArrowLeftFromLine },
  { name: "ArrowRight", icon: ArrowRight },
  { name: "ArrowRightToLine", icon: ArrowRightToLine },
  { name: "ArrowUp10", icon: ArrowUp10 },
  { name: "ArrowUpFromDot", icon: ArrowUpFromDot },
  { name: "ArrowUpNarrowWide", icon: ArrowUpNarrowWide },
  { name: "ArrowUpWideNarrow", icon: ArrowUpWideNarrow },
  { name: "Asterisk", icon: Asterisk },
  { name: "AudioLines", icon: AudioLines },
  { name: "Axe", icon: Axe },
  { name: "Backpack", icon: Backpack },
  { name: "BadgeCent", icon: BadgeCent },
  { name: "BadgeEuro", icon: BadgeEuro },
  { name: "BadgeJapaneseYen", icon: BadgeJapaneseYen },
  { name: "BadgePlus", icon: BadgePlus },
  { name: "BadgeRussianRuble", icon: BadgeRussianRuble },
  { name: "BadgeX", icon: BadgeX },
  { name: "Ban", icon: Ban },
  { name: "Banknote", icon: Banknote },
  { name: "BanknoteX", icon: BanknoteX },
  { name: "Baseline", icon: Baseline },
  { name: "BatteryCharging", icon: BatteryCharging },
  { name: "BatteryMedium", icon: BatteryMedium },
  { name: "Beaker", icon: Beaker },
  { name: "Bed", icon: Bed },
  { name: "Beef", icon: Beef },
  { name: "Bell", icon: Bell },
  { name: "BellMinus", icon: BellMinus },
  { name: "BellRing", icon: BellRing },
  { name: "BetweenVerticalEnd", icon: BetweenVerticalEnd },
  { name: "Bike", icon: Bike },
  { name: "Biohazard", icon: Biohazard },
  { name: "Bitcoin", icon: Bitcoin },
  { name: "Blocks", icon: Blocks },
  { name: "BluetoothOff", icon: BluetoothOff },
  { name: "Bolt", icon: Bolt },
  { name: "Book", icon: Book },
  { name: "BookAudio", icon: BookAudio },
  { name: "BookDashed", icon: BookDashed },
  { name: "BookHeart", icon: BookHeart },
  { name: "BookLock", icon: BookLock },
  { name: "BookOpen", icon: BookOpen },
  { name: "BookPlus", icon: BookPlus },
  { name: "BookType", icon: BookType },
  { name: "BookX", icon: BookX },
  { name: "BookmarkMinus", icon: BookmarkMinus },
  { name: "BoomBox", icon: BoomBox },
  { name: "BotOff", icon: BotOff },
  { name: "Box", icon: Box },
  { name: "Brackets", icon: Brackets },
  { name: "BrainCog", icon: BrainCog },
  { name: "BrickWallShield", icon: BrickWallShield },
  { name: "BriefcaseConveyorBelt", icon: BriefcaseConveyorBelt },
  { name: "Brush", icon: Brush },
  { name: "Bug", icon: Bug },
  { name: "Building", icon: Building },
  { name: "Cable", icon: Cable },
  { name: "CakeSlice", icon: CakeSlice },
  { name: "Calendar1", icon: Calendar1 },
  { name: "CalendarCheck", icon: CalendarCheck },
  { name: "CalendarDays", icon: CalendarDays },
  { name: "CalendarMinus", icon: CalendarMinus },
  { name: "CalendarRange", icon: CalendarRange },
  { name: "CalendarX", icon: CalendarX },
  { name: "CameraOff", icon: CameraOff },
  { name: "CandyOff", icon: CandyOff },
  { name: "Captions", icon: Captions },
  { name: "CarFront", icon: CarFront },
  { name: "CardSim", icon: CardSim },
  { name: "CaseSensitive", icon: CaseSensitive },
  { name: "Cast", icon: Cast },
  { name: "Cctv", icon: Cctv },
  { name: "ChartBarBig", icon: ChartBarBig },
  { name: "ChartBarStacked", icon: ChartBarStacked },
  { name: "ChartColumnBig", icon: ChartColumnBig },
  { name: "ChartColumnStacked", icon: ChartColumnStacked },
  { name: "ChartNetwork", icon: ChartNetwork },
  { name: "ChartNoAxesColumnIncreasing", icon: ChartNoAxesColumnIncreasing },
  { name: "ChartPie", icon: ChartPie },
  { name: "Check", icon: Check },
  { name: "ChefHat", icon: ChefHat },
  { name: "ChessKing", icon: ChessKing },
  { name: "ChessQueen", icon: ChessQueen },
  { name: "ChevronFirst", icon: ChevronFirst },
  { name: "ChevronRight", icon: ChevronRight },
  { name: "ChevronsDownUp", icon: ChevronsDownUp },
  { name: "ChevronsLeftRightEllipsis", icon: ChevronsLeftRightEllipsis },
  { name: "ChevronsUp", icon: ChevronsUp },
  { name: "Church", icon: Church },
  { name: "Circle", icon: Circle },
  { name: "CircleArrowLeft", icon: CircleArrowLeft },
  { name: "CircleArrowOutUpLeft", icon: CircleArrowOutUpLeft },
  { name: "CircleArrowUp", icon: CircleArrowUp },
  { name: "CircleChevronDown", icon: CircleChevronDown },
  { name: "CircleChevronUp", icon: CircleChevronUp },
  { name: "CircleDollarSign", icon: CircleDollarSign },
  { name: "CircleEllipsis", icon: CircleEllipsis },
  { name: "CircleFadingPlus", icon: CircleFadingPlus },
  { name: "CircleOff", icon: CircleOff },
  { name: "CirclePause", icon: CirclePause },
  { name: "CirclePlay", icon: CirclePlay },
  { name: "CirclePower", icon: CirclePower },
  { name: "CircleSmall", icon: CircleSmall },
  { name: "CircleUser", icon: CircleUser },
  { name: "CircuitBoard", icon: CircuitBoard },
  { name: "Clipboard", icon: Clipboard },
  { name: "ClipboardCopy", icon: ClipboardCopy },
  { name: "ClipboardPaste", icon: ClipboardPaste },
  { name: "ClipboardPlus", icon: ClipboardPlus },
  { name: "Clock", icon: Clock },
  { name: "Clock11", icon: Clock11 },
  { name: "Clock5", icon: Clock5 },
  { name: "Clock8", icon: Clock8 },
  { name: "ClockArrowDown", icon: ClockArrowDown },
  { name: "ClockFading", icon: ClockFading },
  { name: "Cloud", icon: Cloud },
  { name: "CloudCheck", icon: CloudCheck },
  { name: "CloudDrizzle", icon: CloudDrizzle },
  { name: "CloudLightning", icon: CloudLightning },
  { name: "CloudOff", icon: CloudOff },
  { name: "CloudSnow", icon: CloudSnow },
  { name: "CloudSync", icon: CloudSync },
  { name: "Clover", icon: Clover },
  { name: "CodeXml", icon: CodeXml },
  { name: "Coffee", icon: Coffee },
  { name: "Columns3", icon: Columns3 },
  { name: "Combine", icon: Combine },
  { name: "Component", icon: Component },
  { name: "Cone", icon: Cone },
  { name: "ContactRound", icon: ContactRound },
  { name: "Cookie", icon: Cookie },
  { name: "CopyCheck", icon: CopyCheck },
  { name: "CopySlash", icon: CopySlash },
  { name: "Copyright", icon: Copyright },
  { name: "CornerLeftDown", icon: CornerLeftDown },
  { name: "CornerRightUp", icon: CornerRightUp },
  { name: "Cpu", icon: Cpu },
  { name: "Croissant", icon: Croissant },
  { name: "Crosshair", icon: Crosshair },
  { name: "CupSoda", icon: CupSoda },
  { name: "Dam", icon: Dam },
  { name: "DatabaseSearch", icon: DatabaseSearch },
  { name: "DecimalsArrowRight", icon: DecimalsArrowRight },
  { name: "Diameter", icon: Diameter },
  { name: "DiamondPercent", icon: DiamondPercent },
  { name: "Dice3", icon: Dice3 },
  { name: "Dice6", icon: Dice6 },
  { name: "Disc", icon: Disc },
  { name: "Divide", icon: Divide },
  { name: "Dock", icon: Dock },
  { name: "Donut", icon: Donut },
  { name: "DoorOpen", icon: DoorOpen },
  { name: "DraftingCompass", icon: DraftingCompass },
  { name: "Drill", icon: Drill },
  { name: "DropletOff", icon: DropletOff },
  { name: "Drumstick", icon: Drumstick },
  { name: "EarOff", icon: EarOff },
  { name: "Eclipse", icon: Eclipse },
  { name: "EggOff", icon: EggOff },
  { name: "Equal", icon: Equal },
  { name: "Eraser", icon: Eraser },
  { name: "EvCharger", icon: EvCharger },
  { name: "Eye", icon: Eye },
  { name: "Facebook", icon: Facebook },
  { name: "FastForward", icon: FastForward },
  { name: "FerrisWheel", icon: FerrisWheel },
  { name: "FileArchive", icon: FileArchive },
  { name: "FileBox", icon: FileBox },
  { name: "FileChartColumn", icon: FileChartColumn },
  { name: "FileChartPie", icon: FileChartPie },
  { name: "FileClock", icon: FileClock },
  { name: "FileCog", icon: FileCog },
  { name: "FileDown", icon: FileDown },
  { name: "FileHeart", icon: FileHeart },
  { name: "FileKey", icon: FileKey },
  { name: "FileMinusCorner", icon: FileMinusCorner },
  { name: "FilePen", icon: FilePen },
  { name: "FilePlus", icon: FilePlus },
  { name: "FileScan", icon: FileScan },
  { name: "FileSignal", icon: FileSignal },
  { name: "FileStack", icon: FileStack },
  { name: "FileText", icon: FileText },
  { name: "FileUp", icon: FileUp },
  { name: "FileVolume", icon: FileVolume },
  { name: "Files", icon: Files },
  { name: "FireExtinguisher", icon: FireExtinguisher },
  { name: "FishSymbol", icon: FishSymbol },
  { name: "FlagOff", icon: FlagOff },
  { name: "Flame", icon: Flame },
  { name: "FlashlightOff", icon: FlashlightOff },
  { name: "FlaskRound", icon: FlaskRound },
  { name: "Flower", icon: Flower },
  { name: "FoldVertical", icon: FoldVertical },
  { name: "FolderCheck", icon: FolderCheck },
  { name: "FolderCode", icon: FolderCode },
  { name: "FolderDown", icon: FolderDown },
  { name: "FolderInput", icon: FolderInput },
  { name: "FolderLock", icon: FolderLock },
  { name: "FolderOpenDot", icon: FolderOpenDot },
  { name: "FolderPlus", icon: FolderPlus },
  { name: "FolderSymlink", icon: FolderSymlink },
  { name: "FolderUp", icon: FolderUp },
  { name: "Footprints", icon: Footprints },
  { name: "Forward", icon: Forward },
  { name: "Frown", icon: Frown },
  { name: "Funnel", icon: Funnel },
  { name: "GalleryHorizontal", icon: GalleryHorizontal },
  { name: "GalleryVertical", icon: GalleryVertical },
  { name: "GamepadDirectional", icon: GamepadDirectional },
  { name: "Gem", icon: Gem },
  { name: "Gift", icon: Gift },
  { name: "GitBranchPlus", icon: GitBranchPlus },
  { name: "GitCompare", icon: GitCompare },
  { name: "GitGraph", icon: GitGraph },
  { name: "GitPullRequestArrow", icon: GitPullRequestArrow },
  { name: "GitPullRequestCreateArrow", icon: GitPullRequestCreateArrow },
  { name: "Gitlab", icon: Gitlab },
  { name: "Globe", icon: Globe },
  { name: "Goal", icon: Goal },
  { name: "Grape", icon: Grape },
  { name: "Grid2x2X", icon: Grid2x2X },
  { name: "GripHorizontal", icon: GripHorizontal },
  { name: "Guitar", icon: Guitar },
  { name: "Hammer", icon: Hammer },
  { name: "HandFist", icon: HandFist },
  { name: "HandHelping", icon: HandHelping },
  { name: "Handbag", icon: Handbag },
  { name: "HardDriveDownload", icon: HardDriveDownload },
  { name: "Hash", icon: Hash },
  { name: "Hd", icon: Hd },
  { name: "Heading1", icon: Heading1 },
  { name: "Heading5", icon: Heading5 },
  { name: "Headphones", icon: Headphones },
  { name: "HeartCrack", icon: HeartCrack },
  { name: "HeartOff", icon: HeartOff },
  { name: "Heater", icon: Heater },
  { name: "Highlighter", icon: Highlighter },
  { name: "HopOff", icon: HopOff },
  { name: "Hourglass", icon: Hourglass },
  { name: "HousePlug", icon: HousePlug },
  { name: "IceCreamBowl", icon: IceCreamBowl },
  { name: "IdCard", icon: IdCard },
  { name: "ImageDown", icon: ImageDown },
  { name: "ImagePlay", icon: ImagePlay },
  { name: "ImageUpscale", icon: ImageUpscale },
  { name: "Inbox", icon: Inbox },
  { name: "Info", icon: Info },
  { name: "Italic", icon: Italic },
  { name: "JapaneseYen", icon: JapaneseYen },
  { name: "Kayak", icon: Kayak },
  { name: "KeySquare", icon: KeySquare },
  { name: "KeyboardOff", icon: KeyboardOff },
  { name: "LampDesk", icon: LampDesk },
  { name: "LampWallUp", icon: LampWallUp },
  { name: "Languages", icon: Languages },
  { name: "LaptopMinimalCheck", icon: LaptopMinimalCheck },
  { name: "Laugh", icon: Laugh },
  { name: "LayoutDashboard", icon: LayoutDashboard },
  { name: "LayoutPanelLeft", icon: LayoutPanelLeft },
  { name: "Leaf", icon: Leaf },
  { name: "Library", icon: Library },
  { name: "Ligature", icon: Ligature },
  { name: "LineSquiggle", icon: LineSquiggle },
  { name: "Linkedin", icon: Linkedin },
  { name: "ListChecks", icon: ListChecks },
  { name: "ListCollapse", icon: ListCollapse },
  { name: "ListFilterPlus", icon: ListFilterPlus },
  { name: "ListMinus", icon: ListMinus },
  { name: "ListPlus", icon: ListPlus },
  { name: "ListTodo", icon: ListTodo },
  { name: "ListX", icon: ListX },
  { name: "LoaderPinwheel", icon: LoaderPinwheel },
  { name: "LocateOff", icon: LocateOff },
  { name: "LockKeyholeOpen", icon: LockKeyholeOpen },
  { name: "LogOut", icon: LogOut },
  { name: "Mail", icon: Mail },
  { name: "MailOpen", icon: MailOpen },
  { name: "MailSearch", icon: MailSearch },
  { name: "Mailbox", icon: Mailbox },
  { name: "MapMinus", icon: MapMinus },
  { name: "MapPinCheckInside", icon: MapPinCheckInside },
  { name: "MapPinMinusInside", icon: MapPinMinusInside },
  { name: "MapPinPlus", icon: MapPinPlus },
  { name: "MapPinXInside", icon: MapPinXInside },
  { name: "Mars", icon: Mars },
  { name: "Maximize", icon: Maximize },
  { name: "MegaphoneOff", icon: MegaphoneOff },
  { name: "Menu", icon: Menu },
  { name: "MessageCircleCode", icon: MessageCircleCode },
  { name: "MessageCircleMore", icon: MessageCircleMore },
  { name: "MessageCircleQuestionMark", icon: MessageCircleQuestionMark },
  { name: "MessageCircleX", icon: MessageCircleX },
  { name: "MessageSquareDashed", icon: MessageSquareDashed },
  { name: "MessageSquareHeart", icon: MessageSquareHeart },
  { name: "MessageSquareOff", icon: MessageSquareOff },
  { name: "MessageSquareReply", icon: MessageSquareReply },
  { name: "MessageSquareWarning", icon: MessageSquareWarning },
  { name: "Mic", icon: Mic },
  { name: "Microchip", icon: Microchip },
  { name: "Milestone", icon: Milestone },
  { name: "Minimize", icon: Minimize },
  { name: "MonitorCheck", icon: MonitorCheck },
  { name: "MonitorDot", icon: MonitorDot },
  { name: "MonitorPause", icon: MonitorPause },
  { name: "MonitorSpeaker", icon: MonitorSpeaker },
  { name: "MonitorX", icon: MonitorX },
  { name: "Motorbike", icon: Motorbike },
  { name: "Mouse", icon: Mouse },
  { name: "MousePointer2Off", icon: MousePointer2Off },
  { name: "Move", icon: Move },
  { name: "MoveDown", icon: MoveDown },
  { name: "MoveHorizontal", icon: MoveHorizontal },
  { name: "MoveUp", icon: MoveUp },
  { name: "MoveVertical", icon: MoveVertical },
  { name: "Music4", icon: Music4 },
  { name: "NavigationOff", icon: NavigationOff },
  { name: "Nfc", icon: Nfc },
  { name: "NotebookPen", icon: NotebookPen },
  { name: "NotepadText", icon: NotepadText },
  { name: "NutOff", icon: NutOff },
  { name: "OctagonMinus", icon: OctagonMinus },
  { name: "Omega", icon: Omega },
  { name: "Origami", icon: Origami },
  { name: "PackageMinus", icon: PackageMinus },
  { name: "PackageSearch", icon: PackageSearch },
  { name: "PaintRoller", icon: PaintRoller },
  { name: "Palette", icon: Palette },
  { name: "PanelBottomClose", icon: PanelBottomClose },
  { name: "PanelLeft", icon: PanelLeft },
  { name: "PanelLeftOpen", icon: PanelLeftOpen },
  { name: "PanelRightClose", icon: PanelRightClose },
  { name: "PanelTop", icon: PanelTop },
  { name: "PanelTopDashed", icon: PanelTopDashed },
  { name: "PanelsRightBottom", icon: PanelsRightBottom },
  { name: "Parentheses", icon: Parentheses },
  { name: "Pause", icon: Pause },
  { name: "Pen", icon: Pen },
  { name: "PenTool", icon: PenTool },
  { name: "PencilOff", icon: PencilOff },
  { name: "Percent", icon: Percent },
  { name: "Phone", icon: Phone },
  { name: "PhoneIncoming", icon: PhoneIncoming },
  { name: "PhoneOutgoing", icon: PhoneOutgoing },
  { name: "Pickaxe", icon: Pickaxe },
  { name: "Pilcrow", icon: Pilcrow },
  { name: "Pill", icon: Pill },
  { name: "PinOff", icon: PinOff },
  { name: "Plane", icon: Plane },
  { name: "Play", icon: Play },
  { name: "Plus", icon: Plus },
  { name: "Podcast", icon: Podcast },
  { name: "Popcorn", icon: Popcorn },
  { name: "Power", icon: Power },
  { name: "Printer", icon: Printer },
  { name: "Projector", icon: Projector },
  { name: "Pyramid", icon: Pyramid },
  { name: "Rabbit", icon: Rabbit },
  { name: "Radical", icon: Radical },
  { name: "RadioTower", icon: RadioTower },
  { name: "Rainbow", icon: Rainbow },
  { name: "Receipt", icon: Receipt },
  { name: "ReceiptIndianRupee", icon: ReceiptIndianRupee },
  { name: "ReceiptRussianRuble", icon: ReceiptRussianRuble },
  { name: "ReceiptTurkishLira", icon: ReceiptTurkishLira },
  { name: "RectangleGoggles", icon: RectangleGoggles },
  { name: "Recycle", icon: Recycle },
  { name: "RefreshCcw", icon: RefreshCcw },
  { name: "RefreshCwOff", icon: RefreshCwOff },
  { name: "RemoveFormatting", icon: RemoveFormatting },
  { name: "Replace", icon: Replace },
  { name: "ReplyAll", icon: ReplyAll },
  { name: "Rocket", icon: Rocket },
  { name: "Rose", icon: Rose },
  { name: "RotateCcwKey", icon: RotateCcwKey }
]

export const ICONS: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.icon])
)

export const COLOR_PALETTE = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#14b8a6", "#06b6d4",
  "#3b82f6", "#6366f1", "#8b5cf6", "#a855f7",
  "#d946ef", "#ec4899", "#f43f5e", "#78716c",
]
