import {
  Activity,
  Airplay,
  AlarmClock,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  Banknote,
  Battery,
  BatteryCharging,
  Beaker,
  Bell,
  Bike,
  Binary,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Command,
  Compass,
  Contact,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Delete,
  Disc,
  Divide,
  DollarSign,
  Download,
  Droplet,
  Dumbbell,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  File,
  FileDigit,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Flag,
  Flame,
  Flashlight,
  Folder,
  FolderKanban,
  FolderOpen,
  Frown,
  FunctionSquare,
  Gamepad2,
  Gauge,
  Ghost,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grid,
  Hammer,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Italic,
  Key,
  Keyboard,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutList,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2,
  List,
  ListChecks,
  ListMusic,
  ListOrdered,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Medal,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minus,
  Monitor,
  MonitorSpeaker,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MousePointer,
  MousePointer2,
  MousePointerClick,
  Move,
  Music,
  Navigation,
  Navigation2,
  Network,
  Octagon,
  Package,
  Palette,
  Palmtree,
  Paperclip,
  Pause,
  PauseCircle,
  PenLine,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Pin,
  Plane,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  RadioReceiver,
  RectangleHorizontal,
  RectangleVertical,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  Rocket,
  RotateCcw,
  RotateCw,
  Router,
  Rss,
  Save,
  Scale,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Sparkles,
  Speaker,
  Square,
  Star,
  Sticker,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Trash,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  Wrench,
  X,
  XCircle,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react"

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: "Star", icon: Star },
  { name: "LayoutList", icon: LayoutList },
  { name: "Tags", icon: Tags },
  { name: "Inbox", icon: Inbox },
  { name: "ListChecks", icon: ListChecks },
  { name: "Brain", icon: Brain },
  { name: "Phone", icon: Phone },
  { name: "Smartphone", icon: Smartphone },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Home", icon: Home },
  { name: "Briefcase", icon: Briefcase },
  { name: "Rocket", icon: Rocket },
  { name: "Zap", icon: Zap },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Target", icon: Target },
  { name: "Flag", icon: Flag },
  { name: "Users", icon: Users },
  { name: "Heart", icon: Heart },
  { name: "Smile", icon: Smile },
  { name: "Gift", icon: Gift },
  { name: "Bell", icon: Bell },
  { name: "Eye", icon: Eye },
  { name: "Search", icon: Search },
  { name: "Laptop", icon: Laptop },
  { name: "Monitor", icon: Monitor },
  { name: "Terminal", icon: Terminal },
  { name: "Code", icon: Code },
  { name: "Database", icon: Database },
  { name: "Wifi", icon: Wifi },
  { name: "Layers", icon: Layers },
  { name: "FileText", icon: FileText },
  { name: "Book", icon: Book },
  { name: "PenLine", icon: PenLine },
  { name: "Paperclip", icon: Paperclip },
  { name: "Palette", icon: Palette },
  { name: "Camera", icon: Camera },
  { name: "Video", icon: Video },
  { name: "Music", icon: Music },
  { name: "Headphones", icon: Headphones },
  { name: "Tv", icon: Tv },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Coffee", icon: Coffee },
  { name: "Utensils", icon: Utensils },
  { name: "Wallet", icon: Wallet },
  { name: "CreditCard", icon: CreditCard },
  { name: "DollarSign", icon: DollarSign },
  { name: "Car", icon: Car },
  { name: "Plane", icon: Plane },
  { name: "Bike", icon: Bike },
  { name: "MapPin", icon: MapPin },
  { name: "Globe", icon: Globe },
  { name: "TreePine", icon: TreePine },
  { name: "Mountain", icon: Mountain },
  { name: "Palmtree", icon: Palmtree },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Cloud", icon: Cloud },
  { name: "Umbrella", icon: Umbrella },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Activity", icon: Activity },
  { name: "Beaker", icon: Beaker },
  { name: "Hammer", icon: Hammer },
  { name: "Wrench", icon: Wrench },
  { name: "Settings", icon: Settings },
  { name: "Lock", icon: Lock },
  { name: "Key", icon: Key },
  { name: "Shield", icon: Shield },
  { name: "Clock", icon: Clock },
  { name: "Calendar", icon: Calendar },
]

export const ICONS: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.icon])
)

export const COLOR_PALETTE = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#14b8a6", "#06b6d4",
  "#3b82f6", "#6366f1", "#8b5cf6", "#a855f7",
  "#d946ef", "#ec4899", "#f43f5e", "#78716c",
]
