import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Ambulance,
  Amphora,
  Annoyed,
  Apple,
  Asterisk,
  AudioLines,
  Axe,
  Backpack,
  Ban,
  Banana,
  Bandage,
  Barcode,
  Bed,
  Beef,
  Beer,
  BeerOff,
  Bike,
  Blocks,
  Bolt,
  Book,
  BookHeart,
  BoomBox,
  BottleWine,
  Box,
  Brackets,
  BrainCog,
  Bug,
  Building,
  Cake,
  CakeSlice,
  Calendar1,
  CalendarCheck,
  CalendarDays,
  CalendarMinus,
  CalendarRange,
  CameraOff,
  Candy,
  CandyCane,
  CandyOff,
  CarFront,
  CardSim,
  Carrot,
  ChartBarStacked,
  ChartColumnBig,
  ChartPie,
  Check,
  ChefHat,
  Cherry,
  ChessKing,
  ChessQueen,
  Church,
  Circle,
  CircleEllipsis,
  CirclePause,
  CirclePlay,
  CircleSmall,
  CircleUser,
  Citrus,
  Clipboard,
  Cloud,
  CloudCheck,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudSnow,
  CloudSync,
  Clover,
  CodeXml,
  Coffee,
  Compass,
  Component,
  Cone,
  ContactRound,
  Cookie,
  CookingPot,
  CopyCheck,
  CopySlash,
  Croissant,
  CupSoda,
  Cylinder,
  Dice3,
  Dice6,
  Disc,
  Donut,
  DoorOpen,
  Drill,
  DropletOff,
  Drumstick,
  Dumbbell,
  EarOff,
  Eclipse,
  Egg,
  EggFried,
  EggOff,
  Equal,
  Eye,
  FastForward,
  FerrisWheel,
  Fish,
  FishOff,
  FishSymbol,
  Flame,
  Flower,
  Footprints,
  Frown,
  Funnel,
  GamepadDirectional,
  Gem,
  Gift,
  GlassWater,
  Globe,
  Grape,
  Guitar,
  Hamburger,
  Hammer,
  HandHelping,
  Hash,
  Headphones,
  Heart,
  HeartCrack,
  HeartOff,
  HeartPulse,
  Hospital,
  Hotel,
  IceCreamBowl,
  IceCreamCone,
  IdCard,
  Inbox,
  Info,
  Laugh,
  Leaf,
  LeafyGreen,
  ListChecks,
  ListTodo,
  Luggage,
  Mail,
  MailOpen,
  MapPin,
  MapPinCheckInside,
  Medal,
  Menu,
  MessageCircleMore,
  MessageCircleQuestionMark,
  Mic,
  Microwave,
  Milk,
  MilkOff,
  Minimize,
  Moon,
  Motorbike,
  Mountain,
  Music4,
  NotebookPen,
  NotepadText,
  Nut,
  NutOff,
  OctagonMinus,
  Omega,
  Pause,
  Pen,
  PenTool,
  Phone,
  PhoneIncoming,
  PhoneOutgoing,
  Pizza,
  Plane,
  Play,
  Podcast,
  Popcorn,
  Rabbit,
  Rainbow,
  Refrigerator,
  Rocket,
  Rose,
  Salad,
  Sandwich,
  ScanBarcode,
  Search,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Slice,
  Soup,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tag,
  Tags,
  Target,
  Tent,
  Thermometer,
  Timer,
  Trees,
  Trophy,
  User,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Vegan,
  Wheat,
  WheatOff,
  Wine
} from "lucide-react"

export const ICON_OPTIONS: { name: string; icon: any }[] = [
  { name: "Ambulance", icon: Ambulance },
  { name: "Amphora", icon: Amphora },
  { name: "Annoyed", icon: Annoyed },
  { name: "Apple", icon: Apple },
  { name: "Asterisk", icon: Asterisk },
  { name: "AudioLines", icon: AudioLines },
  { name: "Axe", icon: Axe },
  { name: "Backpack", icon: Backpack },
  { name: "Ban", icon: Ban },
  { name: "Bed", icon: Bed },
  { name: "Beef", icon: Beef },
  { name: "Bike", icon: Bike },
  { name: "Blocks", icon: Blocks },
  { name: "Bolt", icon: Bolt },
  { name: "Book", icon: Book },
  { name: "BookHeart", icon: BookHeart },
  { name: "BoomBox", icon: BoomBox },
  { name: "Box", icon: Box },
  { name: "Brackets", icon: Brackets },
  { name: "BrainCog", icon: BrainCog },
  { name: "Bug", icon: Bug },
  { name: "Building", icon: Building },
  { name: "CakeSlice", icon: CakeSlice },
  { name: "Calendar1", icon: Calendar1 },
  { name: "CalendarCheck", icon: CalendarCheck },
  { name: "CalendarDays", icon: CalendarDays },
  { name: "CalendarMinus", icon: CalendarMinus },
  { name: "CalendarRange", icon: CalendarRange },
  { name: "CameraOff", icon: CameraOff },
  { name: "CandyOff", icon: CandyOff },
  { name: "CarFront", icon: CarFront },
  { name: "CardSim", icon: CardSim },
  { name: "ChartBarStacked", icon: ChartBarStacked },
  { name: "ChartColumnBig", icon: ChartColumnBig },
  { name: "ChartPie", icon: ChartPie },
  { name: "Check", icon: Check },
  { name: "ChefHat", icon: ChefHat },
  { name: "ChessKing", icon: ChessKing },
  { name: "ChessQueen", icon: ChessQueen },
  { name: "Church", icon: Church },
  { name: "Circle", icon: Circle },
  { name: "CircleEllipsis", icon: CircleEllipsis },
  { name: "CirclePause", icon: CirclePause },
  { name: "CirclePlay", icon: CirclePlay },
  { name: "CircleSmall", icon: CircleSmall },
  { name: "CircleUser", icon: CircleUser },
  { name: "Clipboard", icon: Clipboard },
  { name: "Cloud", icon: Cloud },
  { name: "CloudCheck", icon: CloudCheck },
  { name: "CloudDrizzle", icon: CloudDrizzle },
  { name: "CloudLightning", icon: CloudLightning },
  { name: "CloudOff", icon: CloudOff },
  { name: "CloudSnow", icon: CloudSnow },
  { name: "CloudSync", icon: CloudSync },
  { name: "Clover", icon: Clover },
  { name: "CodeXml", icon: CodeXml },
  { name: "Coffee", icon: Coffee },
  { name: "Component", icon: Component },
  { name: "Cone", icon: Cone },
  { name: "ContactRound", icon: ContactRound },
  { name: "Cookie", icon: Cookie },
  { name: "CopyCheck", icon: CopyCheck },
  { name: "CopySlash", icon: CopySlash },
  { name: "Croissant", icon: Croissant },
  { name: "CupSoda", icon: CupSoda },
  { name: "Dice3", icon: Dice3 },
  { name: "Dice6", icon: Dice6 },
  { name: "Disc", icon: Disc },
  { name: "Donut", icon: Donut },
  { name: "DoorOpen", icon: DoorOpen },
  { name: "Drill", icon: Drill },
  { name: "DropletOff", icon: DropletOff },
  { name: "Drumstick", icon: Drumstick },
  { name: "EarOff", icon: EarOff },
  { name: "Eclipse", icon: Eclipse },
  { name: "EggOff", icon: EggOff },
  { name: "Equal", icon: Equal },
  { name: "Eye", icon: Eye },
  { name: "FastForward", icon: FastForward },
  { name: "FerrisWheel", icon: FerrisWheel },
  { name: "FishSymbol", icon: FishSymbol },
  { name: "Flame", icon: Flame },
  { name: "Flower", icon: Flower },
  { name: "Footprints", icon: Footprints },
  { name: "Frown", icon: Frown },
  { name: "Funnel", icon: Funnel },
  { name: "GamepadDirectional", icon: GamepadDirectional },
  { name: "Gem", icon: Gem },
  { name: "Gift", icon: Gift },
  { name: "Globe", icon: Globe },
  { name: "Grape", icon: Grape },
  { name: "Guitar", icon: Guitar },
  { name: "Hammer", icon: Hammer },
  { name: "HandHelping", icon: HandHelping },
  { name: "Hash", icon: Hash },
  { name: "Headphones", icon: Headphones },
  { name: "HeartCrack", icon: HeartCrack },
  { name: "HeartOff", icon: HeartOff },
  { name: "IceCreamBowl", icon: IceCreamBowl },
  { name: "IdCard", icon: IdCard },
  { name: "Inbox", icon: Inbox },
  { name: "Info", icon: Info },
  { name: "Laugh", icon: Laugh },
  { name: "Leaf", icon: Leaf },
  { name: "ListChecks", icon: ListChecks },
  { name: "ListTodo", icon: ListTodo },
  { name: "Mail", icon: Mail },
  { name: "MailOpen", icon: MailOpen },
  { name: "MapPinCheckInside", icon: MapPinCheckInside },
  { name: "Menu", icon: Menu },
  { name: "MessageCircleMore", icon: MessageCircleMore },
  { name: "MessageCircleQuestionMark", icon: MessageCircleQuestionMark },
  { name: "Mic", icon: Mic },
  { name: "Minimize", icon: Minimize },
  { name: "Motorbike", icon: Motorbike },
  { name: "Music4", icon: Music4 },
  { name: "NotebookPen", icon: NotebookPen },
  { name: "NotepadText", icon: NotepadText },
  { name: "NutOff", icon: NutOff },
  { name: "OctagonMinus", icon: OctagonMinus },
  { name: "Omega", icon: Omega },
  { name: "Pause", icon: Pause },
  { name: "Pen", icon: Pen },
  { name: "PenTool", icon: PenTool },
  { name: "Phone", icon: Phone },
  { name: "PhoneIncoming", icon: PhoneIncoming },
  { name: "PhoneOutgoing", icon: PhoneOutgoing },
  { name: "Plane", icon: Plane },
  { name: "Play", icon: Play },
  { name: "Podcast", icon: Podcast },
  { name: "Popcorn", icon: Popcorn },
  { name: "Rabbit", icon: Rabbit },
  { name: "Rainbow", icon: Rainbow },
  { name: "Rocket", icon: Rocket },
  { name: "Rose", icon: Rose },
  { name: "LeafyGreen", icon: LeafyGreen },
  { name: "Vegan", icon: Vegan },
  { name: "Carrot", icon: Carrot },
  { name: "Cylinder", icon: Cylinder },
  { name: "Soup", icon: Soup },
  { name: "Banana", icon: Banana },
  { name: "Cherry", icon: Cherry },
  { name: "Citrus", icon: Citrus },
  { name: "Nut", icon: Nut },
  { name: "Pizza", icon: Pizza },
  { name: "Hamburger", icon: Hamburger },
  { name: "Sandwich", icon: Sandwich },
  { name: "Wine", icon: Wine },
  { name: "CookingPot", icon: CookingPot },
  { name: "Candy", icon: Candy },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "ShoppingBasket", icon: ShoppingBasket },
  { name: "Store", icon: Store },
  { name: "Barcode", icon: Barcode },
  { name: "ScanBarcode", icon: ScanBarcode },
  { name: "Tag", icon: Tag },
  { name: "Tags", icon: Tags },
  { name: "Utensils", icon: Utensils },
  { name: "UtensilsCrossed", icon: UtensilsCrossed },
  { name: "Egg", icon: Egg },
  { name: "EggFried", icon: EggFried },
  { name: "Fish", icon: Fish },
  { name: "FishOff", icon: FishOff },
  { name: "Milk", icon: Milk },
  { name: "MilkOff", icon: MilkOff },
  { name: "Salad", icon: Salad },
  { name: "Wheat", icon: Wheat },
  { name: "WheatOff", icon: WheatOff },
  { name: "Beer", icon: Beer },
  { name: "BeerOff", icon: BeerOff },
  { name: "BottleWine", icon: BottleWine },
  { name: "GlassWater", icon: GlassWater },
  { name: "Cake", icon: Cake },
  { name: "IceCreamCone", icon: IceCreamCone },
  { name: "CandyCane", icon: CandyCane },
  { name: "Refrigerator", icon: Refrigerator },
  { name: "Microwave", icon: Microwave },
  { name: "Slice", icon: Slice },
  { name: "Heart", icon: Heart },
  { name: "HeartPulse", icon: HeartPulse },
  { name: "Activity", icon: Activity },
  { name: "Stethoscope", icon: Stethoscope },
  { name: "Syringe", icon: Syringe },
  { name: "Bandage", icon: Bandage },
  { name: "Hospital", icon: Hospital },
  { name: "Thermometer", icon: Thermometer },
  { name: "Hotel", icon: Hotel },
  { name: "MapPin", icon: MapPin },
  { name: "Compass", icon: Compass },
  { name: "Luggage", icon: Luggage },
  { name: "Tent", icon: Tent },
  { name: "Trees", icon: Trees },
  { name: "Mountain", icon: Mountain },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Trophy", icon: Trophy },
  { name: "Medal", icon: Medal },
  { name: "Timer", icon: Timer },
  { name: "Target", icon: Target },
  { name: "User", icon: User },
  { name: "Users", icon: Users },
  { name: "UserPlus", icon: UserPlus },
  { name: "UserCheck", icon: UserCheck },
  { name: "Search", icon: Search },
  { name: "Sparkles", icon: Sparkles },
  { name: "Star", icon: Star }
]

export const ICONS: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.icon])
)

export const COLOR_PALETTE = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#14b8a6", "#06b6d4",
  "#3b82f6", "#6366f1", "#8b5cf6", "#a855f7",
  "#d946ef", "#ec4899", "#f43f5e", "#78716c",
]
